CREATE TABLE %s (
id bigint AUTO_INCREMENT,
wheel_id int,
slice_number tinyint,
slice_label text,
coupon_code varchar(255),
email varchar(50) DEFAULT '',
first_name varchar(50) DEFAULT '',
last_name varchar(50) DEFAULT '',
rules_checked tinyint DEFAULT '0',
ip varchar(50) DEFAULT '',
phone_number varchar(31) DEFAULT '',
user_cookie varchar(32),
referer text,
timestamp int,
coupon_expire_timestamp int DEFAULT '0',
webhooks_http_status int DEFAULT '0',
PRIMARY KEY (id),
KEY wheel_id (wheel_id),
KEY email (email),
KEY ip (ip),
KEY user_cookie (user_cookie),
KEY timestamp (timestamp)
) %s;