CREATE TABLE %s (
id int AUTO_INCREMENT,
wheel_name tinytext,
wheel_hash char(6),
seen_key char(6),
popup_heading_text text,
popup_main_text text,
popup_rules_text text,
popup_win_heading_text text,
popup_win_main_text text,
popup_lose_heading_text text,
popup_lose_main_text text,
popup_header_image text,
email_win_subject text,
email_win_message text,
offers_claimed_text text,
is_live tinyint DEFAULT 0,
show_spin_again tinyint DEFAULT 0,
notify_admin_on_win tinyint DEFAULT 0,
notify_admin_email text,
on_win_url text,
on_lose_url text,
on_win_url_target_blank tinyint DEFAULT 0,
custom_gift_icon text,
custom_background_img text,
manual_open tinyint DEFAULT 0,
manual_open_position tinyint DEFAULT 0,
kiosk_mode tinyint DEFAULT 0,
mailchimp_enabled tinyint DEFAULT 0,
webhooks_enabled tinyint DEFAULT 0,
force_individual_use tinyint DEFAULT 1,
force_usage_limit tinyint DEFAULT 1,
woo_expire_coupons tinyint DEFAULT 0,
offers_claimed_percentage tinyint DEFAULT 70,
show_offers_claimed tinyint DEFAULT 0,
show_coupon_notice tinyint DEFAULT 1,
infinite_has_more_chance tinyint DEFAULT 0,
require_email tinyint DEFAULT 1,
require_first_name tinyint DEFAULT 1,
require_last_name tinyint DEFAULT 0,
require_rules tinyint DEFAULT 1,
require_recaptcha tinyint DEFAULT 0,
require_phone_number tinyint DEFAULT 0,
timed_trigger tinyint DEFAULT 1,
exit_trigger tinyint DEFAULT 1,
coupon_notice_on_top tinyint DEFAULT 0,
apply_coupon_on_close tinyint DEFAULT 0,
prevent_triggers_on_mobile tinyint DEFAULT 0,
ace_mx_check tinyint DEFAULT 1,
ace_email_limit_check tinyint DEFAULT 1,
ace_cookie_limit_check tinyint DEFAULT 0,
ace_ip_limit_check tinyint DEFAULT 0,
ace_phone_number_check tinyint DEFAULT 0,
bind_coupon_to_email tinyint DEFAULT 0,
max_spins_per_user int DEFAULT 1,
reset_counter_days int DEFAULT 0,
wheel_spin_time tinyint DEFAULT 10,
show_popup_after int DEFAULT 20,
show_popup_every int DEFAULT 14,
custom_on_show_popup text,
slice_font_size int DEFAULT 100,
coupon_urgency_timer int DEFAULT 30,
unique_coupon_prefix varchar(10) DEFAULT '',
mailchimp_list_id tinytext,
mailchimp_list_name tinytext,
mailchimp_api_key tinytext,
mailchimp_double_optin tinyint DEFAULT 0,
webhooks_url text,
send_mail_after_spin tinyint DEFAULT 0,
offers_progressbar_color tinytext,
popup_heading_text_color tinytext,
popup_main_text_color tinytext,
popup_background_label tinytext,
popup_background_css text,
popup_preview_key char(32),
popup_impressions int DEFAULT 0,
notice_text_color tinytext,
notice_background_color tinytext,
page_filter text,
locale_filter text,
wheel_gfx tinyint DEFAULT 4,
phone_number_length tinyint DEFAULT 0,
lang_enter_your_email tinytext,
lang_enter_your_first_name tinytext,
lang_enter_your_last_name tinytext,
lang_i_agree tinytext,
lang_spin_button tinytext,
lang_continue_button tinytext,
lang_input_missing tinytext,
lang_no_spins tinytext,
lang_ace_email_check tinytext,
lang_ace_limit_reached tinytext,
lang_coupon_notice tinytext,
lang_enter_phone_number tinytext,
lang_close tinytext,
lang_days tinytext,
lang_spin_again tinytext,
slice1_label text,
slice2_label text,
slice3_label text,
slice4_label text,
slice5_label text,
slice6_label text,
slice7_label text,
slice8_label text,
slice9_label text,
slice10_label text,
slice11_label text,
slice12_label text,
slice1_coupon_code tinytext,
slice2_coupon_code tinytext,
slice3_coupon_code tinytext,
slice4_coupon_code tinytext,
slice5_coupon_code tinytext,
slice6_coupon_code tinytext,
slice7_coupon_code tinytext,
slice8_coupon_code tinytext,
slice9_coupon_code tinytext,
slice10_coupon_code tinytext,
slice11_coupon_code tinytext,
slice12_coupon_code tinytext,
slice1_qty int DEFAULT 0,
slice2_qty int DEFAULT 0,
slice3_qty int DEFAULT 0,
slice4_qty int DEFAULT 0,
slice5_qty int DEFAULT 0,
slice6_qty int DEFAULT 0,
slice7_qty int DEFAULT 0,
slice8_qty int DEFAULT 0,
slice9_qty int DEFAULT 0,
slice10_qty int DEFAULT 0,
slice11_qty int DEFAULT 0,
slice12_qty int DEFAULT 0,
slice1_infinite tinyint DEFAULT 0,
slice2_infinite tinyint DEFAULT 0,
slice3_infinite tinyint DEFAULT 0,
slice4_infinite tinyint DEFAULT 0,
slice5_infinite tinyint DEFAULT 0,
slice6_infinite tinyint DEFAULT 0,
slice7_infinite tinyint DEFAULT 0,
slice8_infinite tinyint DEFAULT 0,
slice9_infinite tinyint DEFAULT 0,
slice10_infinite tinyint DEFAULT 0,
slice11_infinite tinyint DEFAULT 0,
slice12_infinite tinyint DEFAULT 0,
slice1_unique_gen tinyint DEFAULT 0,
slice2_unique_gen tinyint DEFAULT 0,
slice3_unique_gen tinyint DEFAULT 0,
slice4_unique_gen tinyint DEFAULT 0,
slice5_unique_gen tinyint DEFAULT 0,
slice6_unique_gen tinyint DEFAULT 0,
slice7_unique_gen tinyint DEFAULT 0,
slice8_unique_gen tinyint DEFAULT 0,
slice9_unique_gen tinyint DEFAULT 0,
slice10_unique_gen tinyint DEFAULT 0,
slice11_unique_gen tinyint DEFAULT 0,
slice12_unique_gen tinyint DEFAULT 0,
slice1_win_multiplier int DEFAULT 12,
slice2_win_multiplier int DEFAULT 12,
slice3_win_multiplier int DEFAULT 12,
slice4_win_multiplier int DEFAULT 12,
slice5_win_multiplier int DEFAULT 12,
slice6_win_multiplier int DEFAULT 12,
slice7_win_multiplier int DEFAULT 12,
slice8_win_multiplier int DEFAULT 12,
slice9_win_multiplier int DEFAULT 12,
slice10_win_multiplier int DEFAULT 12,
slice11_win_multiplier int DEFAULT 12,
slice12_win_multiplier int DEFAULT 12,
user_filter tinyint DEFAULT 0,
PRIMARY KEY (id)
) %s;